# serverless.yml

service: apollo-lambda
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  runtime: nodejs10.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/main.graphqlHandler
    #    environment:
    #      PORT: 4005
    #      APOLLO_INTROSPECTION: true
    #      APOLLO_PLAYGROUND: true
    #      LAMBDA: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
custom:
  webpack:
    webpackConfig: "webpack.prod.js"
    packager: "yarn"
    includeModules: true
  customDomain:
    domainName: test-graphql.hsol.io
    basePath: graphql
    stage: ${self:provider.stage}
    certificateName: "test-graphql.hsol.io"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
